// Mocks generated by Mockito 5.1.0 from annotations
// in individual_project/test/movie_bloc/movie_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:individual_project/data/dao/movie_dao.dart' as _i10;
import 'package:individual_project/model/cast.dart' as _i9;
import 'package:individual_project/model/ganre.dart' as _i7;
import 'package:individual_project/model/ganre_movie_id.dart' as _i11;
import 'package:individual_project/model/movie.dart' as _i6;
import 'package:individual_project/model/movie_detail.dart' as _i2;
import 'package:individual_project/model/person.dart' as _i3;
import 'package:individual_project/model/screenshot.dart' as _i8;
import 'package:individual_project/service/api_moviedb.dart' as _i4;
import 'package:individual_project/service/moviedb.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMovieDetail_0 extends _i1.Fake implements _i2.MovieDetail {}

class _FakePerson_1 extends _i1.Fake implements _i3.Person {}

/// A class which mocks [ApiMovieDb].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiMovieDb extends _i1.Mock implements _i4.ApiMovieDb {
  MockApiMovieDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Movie>> getNowPlayingMovie() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovie, []),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  _i5.Future<List<_i6.Movie>> getPopularMovie() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovie, []),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  _i5.Future<List<_i7.Ganre>> getGenreList() =>
      (super.noSuchMethod(Invocation.method(#getGenreList, []),
              returnValue: Future<List<_i7.Ganre>>.value(<_i7.Ganre>[]))
          as _i5.Future<List<_i7.Ganre>>);
  @override
  _i5.Future<List<_i6.Movie>> getMovieByGanre(int? selectedGanre) =>
      (super.noSuchMethod(Invocation.method(#getMovieByGanre, [selectedGanre]),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  _i5.Future<_i2.MovieDetail> getMovieDetail(int? movieId) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [movieId]),
              returnValue: Future<_i2.MovieDetail>.value(_FakeMovieDetail_0()))
          as _i5.Future<_i2.MovieDetail>);
  @override
  _i5.Future<List<_i8.Screenshot>> getMovieImage(int? movieId) =>
      (super.noSuchMethod(Invocation.method(#getMovieImage, [movieId]),
              returnValue:
                  Future<List<_i8.Screenshot>>.value(<_i8.Screenshot>[]))
          as _i5.Future<List<_i8.Screenshot>>);
  @override
  _i5.Future<List<_i9.Cast>> getCastList(int? movieId) =>
      (super.noSuchMethod(Invocation.method(#getCastList, [movieId]),
              returnValue: Future<List<_i9.Cast>>.value(<_i9.Cast>[]))
          as _i5.Future<List<_i9.Cast>>);
  @override
  _i5.Future<_i3.Person> getPerson(int? personId) =>
      (super.noSuchMethod(Invocation.method(#getPerson, [personId]),
              returnValue: Future<_i3.Person>.value(_FakePerson_1()))
          as _i5.Future<_i3.Person>);
  @override
  _i5.Future<List<_i6.Movie>> getSearchMovieList(String? query) =>
      (super.noSuchMethod(Invocation.method(#getSearchMovieList, [query]),
              returnValue: Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
}

/// A class which mocks [MovieDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDao extends _i1.Mock implements _i10.MovieDao {
  MockMovieDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.Movie>> findMovieByGanre(int? selectedGanre) =>
      (super.noSuchMethod(Invocation.method(#findMovieByGanre, [selectedGanre]),
              returnValue: Stream<List<_i6.Movie>>.empty())
          as _i5.Stream<List<_i6.Movie>>);
  @override
  _i5.Stream<List<_i6.Movie>> findAllMovie() =>
      (super.noSuchMethod(Invocation.method(#findAllMovie, []),
              returnValue: Stream<List<_i6.Movie>>.empty())
          as _i5.Stream<List<_i6.Movie>>);
  @override
  _i5.Stream<List<_i7.Ganre>> findAllGanre() =>
      (super.noSuchMethod(Invocation.method(#findAllGanre, []),
              returnValue: Stream<List<_i7.Ganre>>.empty())
          as _i5.Stream<List<_i7.Ganre>>);
  @override
  _i5.Future<void> insertMovie(_i6.Movie? movie) =>
      (super.noSuchMethod(Invocation.method(#insertMovie, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> insertGanre(_i7.Ganre? ganre) =>
      (super.noSuchMethod(Invocation.method(#insertGanre, [ganre]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> insertGanreAndMovie(_i11.GanreAndMovie? ganreAndMovie) =>
      (super.noSuchMethod(
          Invocation.method(#insertGanreAndMovie, [ganreAndMovie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<List<int>> insertListMovie(List<_i6.Movie>? movie) =>
      (super.noSuchMethod(Invocation.method(#insertListMovie, [movie]),
              returnValue: Future<List<int>>.value(<int>[]))
          as _i5.Future<List<int>>);
  @override
  _i5.Future<List<int>> insertListGanre(List<_i7.Ganre>? ganre) =>
      (super.noSuchMethod(Invocation.method(#insertListGanre, [ganre]),
              returnValue: Future<List<int>>.value(<int>[]))
          as _i5.Future<List<int>>);
  @override
  _i5.Future<void> deleteAllMovies() =>
      (super.noSuchMethod(Invocation.method(#deleteAllMovies, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllGanreAndMovies() =>
      (super.noSuchMethod(Invocation.method(#deleteAllGanreAndMovies, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteAllGanre() =>
      (super.noSuchMethod(Invocation.method(#deleteAllGanre, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> deleteMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteMovieById, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> replaceMovies(List<_i6.Movie>? movie) =>
      (super.noSuchMethod(Invocation.method(#replaceMovies, [movie]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> createGanreList({_i12.MovieDB? apiMovieDb}) =>
      (super.noSuchMethod(
          Invocation.method(#createGanreList, [], {#apiMovieDb: apiMovieDb}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> createMovieList(
          {_i12.MovieDB? apiMovieDb, int? selectedGanre}) =>
      (super.noSuchMethod(
          Invocation.method(#createMovieList, [],
              {#apiMovieDb: apiMovieDb, #selectedGanre: selectedGanre}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}
